# Generated by Django 4.1.1 on 2022-09-11 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opcion',
            old_name='opction_texto',
            new_name='opcion_texto',
        ),
    ]
